import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Button } from "~/components/ui/button";
import { ModeToggle } from "~/components/ModeToggle";
import Shortener from "~/components/shortener";
import DashCard from "~/components/dashcard";
import { SkeletonDashCard } from "~/components/skeletonDashcard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Short-Me</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Short <span className="text-[hsl(280,100%,70%)]">-</span> Me
          </h1>
          <p className="text-2xl text-[hsl(280,100%,70%)]">
            A simple but fast URL shortener
          </p>

          <ModeToggle />
          <Shortener />
        </div>
        <div className="container flex flex-col items-center justify-center px-4 ">
          <DashCard
            avatarSrc="https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
            username="mnlade"
            shorturl="short-me/l/qwer123"
            url="https://github.com/mnlade/short-me"
          />
          <SkeletonDashCard />
          <SkeletonDashCard />
          <SkeletonDashCard />
        </div>
        <div className="flex flex-col items-center gap-2">
          <AuthShowcase />
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {/* {secretMessage && <span> - {secretMessage}</span>} */}
      </p>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </div>
  );
}
